Repository offalynne/Input, pull requests merged in 2022-07, with the labels that each got.

#395 Blacklist and icon cleanup
  scripts/__input_config_icons/__input_config_icons.gml
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
  scripts/__input_sdl2_database_funcs/__input_sdl2_database_funcs.gml
Labels: bug :sweat_smile:, device-gamepad 🎾

#401 docs: fixes for yyg manual links (5.0 docs only)
  docs/5.0/Controller-Mapping.md
  docs/5.0/Functions-(Binding-Access).md
  docs/5.0/Functions-(Binding-Creators).md
  docs/5.0/Functions-(Gamepad).md
  docs/5.0/Functions-(Mouse).md
  docs/5.0/Functions-(Other).md
  docs/5.0/Functions-(Players).md
  docs/5.0/Newbie-Guide.md
Labels: documentation ✏️

#398 Detect input on assigned sources
  scripts/input_source_detect_input/input_source_detect_input.gml
Labels: feature :thought_balloon:, device-gamepad 🎾
