Repository offalynne/Input, pull requests merged in 2022-06, with the labels that each got.

#362 Update datafile refresher
  datafiles/sdl2.txt
  refresh_datafiles.py
Labels: device-gamepad 🎾

#364 Documentation for direct functions
  scripts/input_gamepad_check/input_gamepad_check.gml
  scripts/input_gamepad_check_pressed/input_gamepad_check_pressed.gml
  scripts/input_gamepad_check_released/input_gamepad_check_released.gml
  scripts/input_gamepad_constant_get_name/input_gamepad_constant_get_name.gml
  scripts/input_gamepad_get_description/input_gamepad_get_description.gml
  scripts/input_gamepad_get_dpad_style/input_gamepad_get_dpad_style.gml
  scripts/input_gamepad_get_map/input_gamepad_get_map.gml
  scripts/input_gamepad_get_type/input_gamepad_get_type.gml
  scripts/input_gamepad_is_axis/input_gamepad_is_axis.gml
  scripts/input_gamepad_is_connected/input_gamepad_is_connected.gml
  scripts/input_gamepad_value/input_gamepad_value.gml
  scripts/input_gamepads_get_status/input_gamepads_get_status.gml
  scripts/input_keyboard_check/input_keyboard_check.gml
  scripts/input_keyboard_check_pressed/input_keyboard_check_pressed.gml
  scripts/input_keyboard_check_released/input_keyboard_check_released.gml
  scripts/input_mouse_capture_get/input_mouse_capture_get.gml
  scripts/input_mouse_capture_set/input_mouse_capture_set.gml
  scripts/input_mouse_check/input_mouse_check.gml
  scripts/input_mouse_check_pressed/input_mouse_check_pressed.gml
  scripts/input_mouse_check_released/input_mouse_check_released.gml
  scripts/input_mouse_coord_space_get/input_mouse_coord_space_get.gml
  scripts/input_mouse_coord_space_set/input_mouse_coord_space_set.gml
  scripts/input_mouse_dx/input_mouse_dx.gml
  scripts/input_mouse_dy/input_mouse_dy.gml
  scripts/input_mouse_moved/input_mouse_moved.gml
  scripts/input_mouse_x/input_mouse_x.gml
  scripts/input_mouse_y/input_mouse_y.gml
Labels: documentation ✏️

#365 Documentation for Export/Import functions
  scripts/input_player_copy/input_player_copy.gml
  scripts/input_player_export/input_player_export.gml
  scripts/input_player_import/input_player_import.gml
  scripts/input_player_reset/input_player_reset.gml
  scripts/input_profile_copy/input_profile_copy.gml
  scripts/input_profile_export/input_profile_export.gml
  scripts/input_profile_import/input_profile_import.gml
  scripts/input_system_export/input_system_export.gml
  scripts/input_system_import/input_system_import.gml
  scripts/input_system_reset/input_system_reset.gml
Labels: documentation ✏️

#384 Export typo
  scripts/input_system_export/input_system_export.gml
Labels: bug :sweat_smile:

#392 Correctly return trigger axis
  scripts/__input_class_gamepad/__input_class_gamepad.gml
Labels: bug :sweat_smile:, platform-ios 📱, platform-console 📦, device-gamepad 🎾

#394 Print gamepad device properties
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
Labels: feature :thought_balloon:, device-gamepad 🎾
