Repository offalynne/Input, pull requests merged in 2022-08, with the labels that each got.

#424 `XDK` -> `XBOX`
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_source/__input_class_source.gml
  scripts/__input_gamepad_set_description/__input_gamepad_set_description.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_system/__input_system.gml
Labels: feature :thought_balloon:, platform-uwp 🎯

#413 Bump data
  datafiles/controllerblacklist.csv
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
  refresh_datafiles.py
Labels: feature :thought_balloon:, device-gamepad 🎾

#420 Adds Switch controllers for iOS 16
  objects/obj_gamepad_tester/Step_1.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_initialize/__input_initialize.gml
Labels: feature :thought_balloon:, platform-ios 📱, device-gamepad 🎾

#425 Adds Linux Wii Remote and Wii Classic Controller support
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
  scripts/__input_gamepad_set_description/__input_gamepad_set_description.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_initialize/__input_initialize.gml
Labels: feature :thought_balloon:, platform-ubuntu 🐧, device-gamepad 🎾

#426 `input_cursor_elastic_get wrong` number of args fix
  scripts/input_cursor_elastic_get/input_cursor_elastic_get.gml
Labels: bug :sweat_smile:

#432 [5.0] [5.1] Add tabbed sections to Binding Names + Verbs & Bindings Page
  docs/5.0/Binding-Names.md
  docs/5.0/Verbs-and-Bindings.md
  docs/5.1/Binding-Names.md
  docs/5.1/Verbs-and-Bindings.md
Labels: documentation ✏️

#431 Fixes for 5.1 docs 404 links + missing `input_swap_gamepad_ab(state)` desc
  docs/5.1/Binding-Names.md
  docs/5.1/Device-Quirks.md
  docs/5.1/Function-Index.md
  docs/5.1/Functions-(Gamepad).md
  docs/5.1/Gamepad-Button-Labels.md
  docs/5.1/Newbie-Guide.md
  docs/5.1/Platform-Quirks.md
  docs/5.1/Quick-Reference.md
Labels: documentation ✏️

#442 Fixes `input_profile_export`
  scripts/__input_class_player/__input_class_player.gml
Labels: bug :sweat_smile:, request ❓

#435 __input_class_combo_state fix: have only one argument
  scripts/__input_class_combo_state/__input_class_combo_state.gml
Labels: bug :sweat_smile:

#436 Fix crash when `INPUT_MULTIPLAYER_LEAVE_VERB` is undefined
  objects/obj_example_mp_player/Step_0.gml
  scripts/__input_multiplayer_assignment_tick/__input_multiplayer_assignment_tick.gml
Labels: bug :sweat_smile:, device-gamepad 🎾, request ❓

#443 Hotswap fix for PlayStation controllers on Windows
  objects/obj_gamepad_tester/Draw_0.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
Labels: bug :sweat_smile:, platform-windows 💢, device-gamepad 🎾, workaround 🔧, request ❓

#434 Attempt for haptic support ( #341 )
  input.yyp
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_player/__input_class_player.gml
  scripts/__input_config_gamepads/__input_config_gamepads.gml
  scripts/__input_system/__input_system.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/input_vibrate/input_vibrate.gml
  scripts/input_vibrate/input_vibrate.yy
  scripts/input_vibrate_curve/input_vibrate_curve.gml
  scripts/input_vibrate_curve/input_vibrate_curve.yy
Labels: feature :thought_balloon:, platform-windows 💢, platform-console 📦, device-gamepad 🎾

#444 Adds `input_check_opposing_pressed`, renames `repeat_opposing` to `opposing_repeat`
  input.yyp
  objects/obj_example_rebinding/Step_0.gml
  scripts/input_check_opposing_pressed/input_check_opposing_pressed.gml
  scripts/input_check_opposing_pressed/input_check_opposing_pressed.yy
  scripts/input_check_opposing_repeat/input_check_opposing_repeat.gml
  scripts/input_check_opposing_repeat/input_check_opposing_repeat.yy
Labels: feature :thought_balloon:

#421 Adds `input_held_time_released`
  input.yyp
  scripts/input_held_time_released/input_held_time_released.gml
  scripts/input_held_time_released/input_held_time_released.yy
Labels: feature :thought_balloon:

#457 Steam Deck controller compatibility
  input.yyp
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_string_contains/__input_string_contains.gml
  scripts/__input_string_contains/__input_string_contains.yy
Labels: feature :thought_balloon:, platform-ubuntu 🐧, device-gamepad 🎾

#447 reworks `input_check_opposing_pressed`
  scripts/input_check_opposing_pressed/input_check_opposing_pressed.gml
Labels: bug :sweat_smile:
