Repository offalynne/Input, pull requests merged in 2023-03, with the labels that each got.

#608 Adds gamepad type constants
  scripts/__input_class_gamepad_motion/__input_class_gamepad_motion.gml
  scripts/__input_config_icons/__input_config_icons.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/input_binding_get_icon/input_binding_get_icon.gml
  scripts/input_icons/input_icons.gml
  scripts/input_player_gamepad_type_override_set/input_player_gamepad_type_override_set.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#609 Data bump
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
Labels: feature :thought_balloon:, device-gamepad 🎾

#613 Readable warning on gamepad value for keyboard binding
  scripts/__input_class_player/__input_class_player.gml
Labels: bug :sweat_smile:

#621 CHEETS corrections
  scripts/__input_initialize/__input_initialize.gml
Labels: bug :sweat_smile:

#623 Assign all gamepads in mixed and multisource mode
  scripts/__input_system_tick/__input_system_tick.gml
Labels: bug :sweat_smile:, device-gamepad 🎾

#629 Fixes crashing on HTML5
  scripts/__input_initialize/__input_initialize.gml
Labels: upstream bug 💧, platform-web 🕷️, workaround 🔧
