Repository offalynne/Input, pull requests merged in 2023-04, with the labels that each got.

#634 Gyro test warning
  objects/obj_test_cursor_gyro/Create_0.gml
Labels: feature :thought_balloon:, platform-console 📦, device-gamepad 🎾, platform-desktop-native 🖥️

#631 Fixes cursor error (6.0)
  scripts/__input_initialize/__input_initialize.gml
  scripts/input_cursor_previous_x/input_cursor_previous_x.gml
  scripts/input_cursor_previous_y/input_cursor_previous_y.gml
  scripts/input_cursor_x/input_cursor_x.gml
  scripts/input_cursor_y/input_cursor_y.gml
  scripts/input_mouse_dx/input_mouse_dx.gml
  scripts/input_mouse_dy/input_mouse_dy.gml
  scripts/input_mouse_x/input_mouse_x.gml
  scripts/input_mouse_y/input_mouse_y.gml
Labels: bug :sweat_smile:

#626 Assign-all correction for 6.0
  scripts/__input_system_tick/__input_system_tick.gml
Labels: bug :sweat_smile:, device-gamepad 🎾

#630 Normalize vibration for Joy-Cons
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_config_vibration/__input_config_vibration.gml
  scripts/__input_validate_macros/__input_validate_macros.gml
Labels: bug :sweat_smile:, platform-console 📦, device-gamepad 🎾, platform-desktop-native 🖥️

#648 `INPUT_POINTER_TYPE` constant
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
Labels: feature :thought_balloon:, device-mouse 🐈

#644 Gamepad LED pattern getter
  input.yyp
  objects/obj_gamepad_tester/Draw_0.gml
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/input_led_pattern_get/input_led_pattern_get.gml
  scripts/input_led_pattern_get/input_led_pattern_get.yy
Labels: feature :thought_balloon:, platform-ios 📱, platform-console 📦, device-gamepad 🎾, platform-desktop-native 🖥️

#625 Assign gamepads in mixed and multisource modes for <6
  scripts/__input_system_tick/__input_system_tick.gml
Labels: bug :sweat_smile:, device-gamepad 🎾

#647 Adds mouse enabled set/get
  input.yyp
  objects/obj_test_cursor/Draw_0.gml
  scripts/__input_class_cursor/__input_class_cursor.gml
  scripts/__input_class_player/__input_class_player.gml
  scripts/input_mouse_enabled_get/input_mouse_enabled_get.gml
  scripts/input_mouse_enabled_get/input_mouse_enabled_get.yy
  scripts/input_mouse_enabled_set/input_mouse_enabled_set.gml
  scripts/input_mouse_enabled_set/input_mouse_enabled_set.yy
Labels: feature :thought_balloon:, device-mouse 🐈

#653 Bump data
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_initialize/__input_initialize.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#657 Cursor capture fixes
  input.yyp
  objects/obj_test_cursor/Draw_0.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_release_multimonitor_cursor/__input_release_multimonitor_cursor.gml
  scripts/__input_release_multimonitor_cursor/__input_release_multimonitor_cursor.yy
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/__input_window_changed/__input_window_changed.gml
  scripts/__input_window_changed/__input_window_changed.yy
  scripts/input_mouse_capture_get/input_mouse_capture_get.gml
  scripts/input_mouse_capture_set/input_mouse_capture_set.gml
Labels: feature :thought_balloon:, device-mouse 🐈, platform-desktop-native 🖥️

#659 Rethinks optional gamepad types, removes macro
  input.yyp
  scripts/__input_config_gamepads/__input_config_gamepads.gml
  scripts/__input_define_gamepad_types/__input_define_gamepad_types.gml
  scripts/__input_define_gamepad_types/__input_define_gamepad_types.yy
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_validate_macros/__input_validate_macros.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#660 Ran through YYP Maker
  input.yyp
Labels: bug :sweat_smile:, platform-web 🕷️

#668 Fixes JSON undefined/null discrepancy on import
  scripts/__input_class_player/__input_class_player.gml
Labels: bug :sweat_smile:

#669 Bump data
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
Labels: feature :thought_balloon:, device-gamepad 🎾

#670 Adds Switch mappings for hid-nx-dkms on Linux
  datafiles/sdl2.txt
Labels: feature :thought_balloon:, platform-ubuntu 🐧, device-gamepad 🎾
