Repository offalynne/Input, pull requests merged in 2023-05, with the labels that each got.

#678 Revise touch macros
  input.yyp
  objects/obj_gamepad_tester/Step_1.gml
  objects/obj_test_cursor_gyro/Draw_0.gml
  objects/obj_test_touch/Create_0.gml
  objects/obj_test_touch_as_mouse/Create_0.gml
  objects/obj_test_touch_as_mouse/Draw_0.gml
  objects/obj_test_touch_as_mouse/Draw_64.gml
  objects/obj_test_touch_as_mouse/Step_0.gml
  objects/obj_test_touch_as_mouse/obj_test_touch_as_mouse.yy
  objects/obj_test_virtual_buttons/obj_test_virtual_buttons.yy
  scripts/__input_binding_get_label/__input_binding_get_label.gml
  scripts/__input_class_binding/__input_class_binding.gml
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_source/__input_class_source.gml
  scripts/__input_config_gamepads/__input_config_gamepads.gml
  scripts/__input_config_touch/__input_config_touch.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_gamepad_set_vid_pid/__input_gamepad_set_vid_pid.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_player_tick_sources/__input_player_tick_sources.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/__input_validate_macros/__input_validate_macros.gml
  scripts/input_gamepad_get_map/input_gamepad_get_map.gml
  scripts/input_mouse_moved/input_mouse_moved.gml
  scripts/input_source_detect_input/input_source_detect_input.gml
Labels: bug :sweat_smile:, feature :thought_balloon:, platform-windows 💢, platform-android 🤖, platform-ios 📱, platform-console 📦, device-gamepad 🎾, device-touch 🦔

#680 Data bump
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
Labels: feature :thought_balloon:, platform-android 🤖, device-gamepad 🎾, platform-desktop-native 🖥️

#679 Optional gamepad type icons
  scripts/__input_config_icons/__input_config_icons.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#681 Fix touch release bug
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/input_mouse_check_released/input_mouse_check_released.gml
Labels: bug :sweat_smile:, device-touch 🦔

#684 Add log suppression
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_player/__input_class_player.gml
  scripts/__input_class_source/__input_class_source.gml
  scripts/__input_class_virtual/__input_class_virtual.gml
  scripts/__input_finalize_default_profiles/__input_finalize_default_profiles.gml
  scripts/__input_gamepad_find_in_sdl2_database/__input_gamepad_find_in_sdl2_database.gml
  scripts/__input_gamepad_guid_parse/__input_gamepad_guid_parse.gml
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
  scripts/__input_gamepad_set_description/__input_gamepad_set_description.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_gamepad_set_vid_pid/__input_gamepad_set_vid_pid.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_load_blacklist_csv/__input_load_blacklist_csv.gml
  scripts/__input_load_sdl2_from_buffer/__input_load_sdl2_from_buffer.gml
  scripts/__input_load_sdl2_from_file/__input_load_sdl2_from_file.gml
  scripts/__input_load_type_csv/__input_load_type_csv.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/input_ignore_key_add/input_ignore_key_add.gml
Labels: feature :thought_balloon:

#685 Add SDL2 database parsing via new string functions
  input.yyp
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_load_sdl2_from_buffer_legacy/__input_load_sdl2_from_buffer_legacy.gml
  scripts/__input_load_sdl2_from_buffer_legacy/__input_load_sdl2_from_buffer_legacy.yy
  scripts/__input_load_sdl2_from_file/__input_load_sdl2_from_file.gml
  scripts/__input_load_sdl2_from_string/__input_load_sdl2_from_string.gml
  scripts/__input_load_sdl2_from_string_internal/__input_load_sdl2_from_string_internal.gml
  scripts/__input_load_sdl2_from_string_internal/__input_load_sdl2_from_string_internal.yy
Labels: feature :thought_balloon:

#688 `gyro` to `cursor_gyro`
  input.yyp
  objects/obj_test_cursor_gyro/Draw_0.gml
  objects/obj_test_cursor_gyro/Step_1.gml
  scripts/input_cursor_gyro_enabled_get/input_cursor_gyro_enabled_get.gml
  scripts/input_cursor_gyro_enabled_get/input_cursor_gyro_enabled_get.yy
  scripts/input_cursor_gyro_enabled_set/input_cursor_gyro_enabled_set.gml
  scripts/input_cursor_gyro_enabled_set/input_cursor_gyro_enabled_set.yy
  scripts/input_cursor_gyro_params_get/input_cursor_gyro_params_get.gml
  scripts/input_cursor_gyro_params_get/input_cursor_gyro_params_get.yy
  scripts/input_cursor_gyro_params_set/input_cursor_gyro_params_set.gml
  scripts/input_cursor_gyro_params_set/input_cursor_gyro_params_set.yy
  scripts/input_motion_data_get/input_motion_data_get.yy
Labels: feature :thought_balloon:, device-gamepad 🎾, documentation ✏️

#695 Upstream data updates
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
  refresh_datafiles.py
Labels: feature :thought_balloon:, device-gamepad 🎾

#694 YYC fix
  scripts/__input_initialize/__input_initialize.gml
Labels: bug :sweat_smile:, platform-steam 🚂

#698 Allow controller object recovery on restart, add controller object depth definition
  input.yyp
  objects/input_controller_object/Other_3.gml
  objects/input_controller_object/input_controller_object.yy
  objects/obj_example_drop_in_gameplay/Create_0.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_restart_get/__input_restart_get.gml
  scripts/__input_restart_get/__input_restart_get.yy
  scripts/__input_restart_set/__input_restart_set.gml
  scripts/__input_restart_set/__input_restart_set.yy
Labels: bug :sweat_smile:, feature :thought_balloon:

#696 Rework device support macros
  objects/obj_gamepad_tester/Step_1.gml
  objects/obj_test_cursor_gyro/Create_0.gml
  objects/obj_test_touch_as_mouse/Draw_64.gml
  scripts/__input_binding_get_label/__input_binding_get_label.gml
  scripts/__input_class_binding/__input_class_binding.gml
  scripts/__input_class_cursor/__input_class_cursor.gml
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_gamepad_motion/__input_class_gamepad_motion.gml
  scripts/__input_class_player/__input_class_player.gml
  scripts/__input_class_source/__input_class_source.gml
  scripts/__input_config_general/__input_config_general.gml
  scripts/__input_config_touch/__input_config_touch.gml
  scripts/__input_config_vibration/__input_config_vibration.gml
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_gamepad_set_vid_pid/__input_gamepad_set_vid_pid.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_keyboard_key/__input_keyboard_key.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_mouse_button/__input_mouse_button.gml
  scripts/__input_player_tick_sources/__input_player_tick_sources.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/__input_validate_macros/__input_validate_macros.gml
  scripts/input_debug_all_input/input_debug_all_input.gml
  scripts/input_debug_player_input/input_debug_player_input.gml
  scripts/input_gamepad_is_connected/input_gamepad_is_connected.gml
  scripts/input_mouse_check/input_mouse_check.gml
  scripts/input_mouse_check_pressed/input_mouse_check_pressed.gml
  scripts/input_mouse_check_released/input_mouse_check_released.gml
  scripts/input_mouse_in_bounds/input_mouse_in_bounds.gml
  scripts/input_mouse_moved/input_mouse_moved.gml
  scripts/input_source_detect_input/input_source_detect_input.gml
  scripts/input_source_detect_new/input_source_detect_new.gml
  scripts/input_source_set/input_source_set.gml
Labels: feature :thought_balloon:

#699 Publicize general platform Macros
  objects/obj_gamepad_tester/Step_1.gml
  scripts/__input_binding_get_label/__input_binding_get_label.gml
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_player/__input_class_player.gml
  scripts/__input_class_source/__input_class_source.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_vid_pid/__input_gamepad_set_vid_pid.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/__input_mouse_button/__input_mouse_button.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/input_mouse_capture_set/input_mouse_capture_set.gml
  scripts/input_source_detect_new/input_source_detect_new.gml
Labels: feature :thought_balloon:

#700 Virtual keyboard for Steam and mobile
  input.yyp
  scripts/__input_config_touch/__input_config_touch.gml
  scripts/__input_validate_macros/__input_validate_macros.gml
  scripts/input_keyboard_virtual_hide/input_keyboard_virtual_hide.gml
  scripts/input_keyboard_virtual_hide/input_keyboard_virtual_hide.yy
  scripts/input_keyboard_virtual_show/input_keyboard_virtual_show.gml
  scripts/input_keyboard_virtual_show/input_keyboard_virtual_show.yy
Labels: feature :thought_balloon:, platform-android 🤖, platform-ios 📱, device-keyboard 🔨, device-touch 🦔, platform-steam 🚂

#703 Use internals for hotswap performance
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/input_gamepad_check/input_gamepad_check.gml
  scripts/input_gamepad_check_pressed/input_gamepad_check_pressed.gml
  scripts/input_gamepad_check_released/input_gamepad_check_released.gml
  scripts/input_gamepad_value/input_gamepad_value.gml
  scripts/input_source_using/input_source_using.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#706 Reworks AB swap
  input.yyp
  objects/obj_test_trigger_effects/Draw_0.gml
  scripts/__input_class_binding/__input_class_binding.gml
  scripts/__input_class_cursor/__input_class_cursor.gml
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_icon_category/__input_class_icon_category.gml
  scripts/__input_config_gamepads/__input_config_gamepads.gml
  scripts/__input_finalize_default_profiles/__input_finalize_default_profiles.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_gamepad_type_swap_ab/__input_gamepad_type_swap_ab.gml
  scripts/__input_gamepad_type_swap_ab/__input_gamepad_type_swap_ab.yy
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_keyboard_key/__input_keyboard_key.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/__input_validate_macros/__input_validate_macros.gml
  scripts/input_keyboard_virtual_show/input_keyboard_virtual_show.gml
  scripts/input_swap_gamepad_ab/input_swap_gamepad_ab.gml
  scripts/input_swap_gamepad_ab/input_swap_gamepad_ab.yy
Labels: feature :thought_balloon:, device-gamepad 🎾
