Repository offalynne/Input, pull requests merged in 2023-11, with the labels that each got.

#822 Vbutton 1-frame delay fix
  scripts/__input_system_tick/__input_system_tick.gml
Labels: bug :sweat_smile:

#813 Bump data
  datafiles/sdl2.txt
Labels: device-gamepad 🎾

#812 Corrections, hotswap and XInput reworks
  input.yyp
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_class_gamepad_mapping/__input_class_gamepad_mapping.gml
  scripts/__input_config_keyboard/__input_config_keyboard.gml
  scripts/__input_define_gamepad_types/__input_define_gamepad_types.gml
  scripts/__input_gamepad_reset_color/__input_gamepad_reset_color.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_gamepad_stop_trigger_effects/__input_gamepad_stop_trigger_effects.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_system_tick/__input_system_tick.gml
Labels: bug :sweat_smile:, device-keyboard 🔨, device-gamepad 🎾

#819 DRY dpad hat mapping
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
Labels: device-gamepad 🎾

#823 Allow overlay Input
  scripts/__input_class_cursor/__input_class_cursor.gml
  scripts/__input_class_gamepad_mapping/__input_class_gamepad_mapping.gml
  scripts/__input_class_gamepad_motion/__input_class_gamepad_motion.gml
  scripts/__input_hotswap_tick/__input_hotswap_tick.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_system_tick/__input_system_tick.gml
  scripts/input_gamepad_check/input_gamepad_check.gml
  scripts/input_gamepad_check_pressed/input_gamepad_check_pressed.gml
  scripts/input_gamepad_check_released/input_gamepad_check_released.gml
  scripts/input_gamepad_value/input_gamepad_value.gml
  scripts/input_mouse_check/input_mouse_check.gml
  scripts/input_mouse_check_pressed/input_mouse_check_pressed.gml
  scripts/input_mouse_check_released/input_mouse_check_released.gml
  scripts/input_mouse_wheel_down/input_mouse_wheel_down.gml
  scripts/input_mouse_wheel_up/input_mouse_wheel_up.gml
  scripts/input_source_detect_input/input_source_detect_input.gml
Labels: feature :thought_balloon:

#826 Adds `input_players_using_source`
  input.yyp
  scripts/input_players_using_source/input_players_using_source.gml
  scripts/input_players_using_source/input_players_using_source.yy
Labels: feature :thought_balloon:

#829 Fix garbage output from gamepad mapping when disconnecting
  objects/obj_gamepad_tester/Create_0.gml
  objects/obj_gamepad_tester/Draw_0.gml
  scripts/__input_class_gamepad/__input_class_gamepad.gml
Labels: bug :sweat_smile:, device-gamepad 🎾
