Repository offalynne/Input, pull requests merged in 2023-06, with the labels that each got.

#711 Typo correction
  scripts/__input_initialize/__input_initialize.gml
Labels: bug :sweat_smile:

#712 Hardens Deck ID, adds GM Steam warning
  scripts/__input_initialize/__input_initialize.gml
Labels: feature :thought_balloon:, upstream bug 💧, platform-steam 🚂

#713 Update Functions-(Keyboard).md
  docs/6.0/Functions-(Keyboard).md
Labels: documentation ✏️

#716 Docs input mouse check
  docs/6.0/Functions-(Mouse).md
Labels: documentation ✏️

#717 Adds mouse wheel direct checkers
  input.yyp
  scripts/input_icon_empty/input_icons.gml
  scripts/input_icon_not_a_binding/input_icons.gml
  scripts/input_mouse_check_pressed/input_mouse_check_pressed.gml
  scripts/input_mouse_check_released/input_mouse_check_released.gml
  scripts/input_mouse_wheel_down/input_mouse_wheel_down.gml
  scripts/input_mouse_wheel_down/input_mouse_wheel_down.yy
  scripts/input_mouse_wheel_up/input_mouse_wheel_up.gml
  scripts/input_mouse_wheel_up/input_mouse_wheel_up.yy
Labels: feature :thought_balloon:, device-mouse 🐈

#719 Add Anne Pro 2 mapping
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_gamepad_set_vid_pid/__input_gamepad_set_vid_pid.gml
Labels: feature :thought_balloon:, device-gamepad 🎾, platform-desktop-native 🖥️

#726 Clarify controller object depth error
  scripts/__input_initialize/__input_initialize.gml
Labels: bug :sweat_smile:

#728 Don't report blacklist connections
  scripts/input_gamepad_is_connected/input_gamepad_is_connected.gml
Labels: bug :sweat_smile:

#727 Simplify paddle icons, rejig mappings for Xbox Elite, add DualSense Edge icons
  scripts/__input_config_icons/__input_config_icons.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
  scripts/__input_initialize/__input_initialize.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#733 Correct virtual priority
  scripts/__input_class_virtual/__input_class_virtual.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_system_tick/__input_system_tick.gml
Labels: bug :sweat_smile:

#734 Force trigger binding to axis
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/input_binding_gamepad_button/input_binding_gamepad_button.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#735 Reworks mouse and keyboard device filtering on Android
  datafiles/controllerblacklist.csv
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
Labels: feature :thought_balloon:, platform-android 🤖, device-keyboard 🔨, device-mouse 🐈
