Repository offalynne/Input, pull requests merged in 2023-09, with the labels that each got.

#768 Bump data
  datafiles/controllerblacklist.csv
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
  scripts/__input_define_gamepad_types/__input_define_gamepad_types.gml
  scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
Labels: feature :thought_balloon:

#773 Gamepad tester fallback
  objects/obj_gamepad_tester/Create_0.gml
  objects/obj_gamepad_tester/Step_1.gml
Labels: feature :thought_balloon:

#774 Fix coordinate space translation bug
  scripts/__input_transform_coordinate/__input_transform_coordinate.gml
Labels: bug :sweat_smile:

#779 More non-gamepad joystick filtering
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
Labels: feature :thought_balloon:, platform-android 🤖, platform-web 🕷️, device-gamepad 🎾, platform-desktop-native 🖥️

#783 Prevent restart thrashing
  input.yyp
  objects/input_controller_object/Other_3.gml
  scripts/__input_class_gamepad_motion/__input_class_gamepad_motion.gml
  scripts/__input_clear_all/__input_clear_all.gml
  scripts/__input_clear_all/__input_clear_all.yy
  scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_restart/__input_restart.gml
  scripts/__input_restart/__input_restart.yy
  scripts/__input_restart_get/__input_restart_get.gml
  scripts/__input_restart_set/__input_restart_set.gml
  scripts/__input_system_tick/__input_system_tick.gml
Labels: bug :sweat_smile:

#786 Clean up digital trigger handling
  scripts/__input_class_gamepad/__input_class_gamepad.gml
  scripts/__input_macros/__input_macros.gml
  scripts/input_binding_gamepad_axis/input_binding_gamepad_axis.gml
  scripts/input_binding_gamepad_button/input_binding_gamepad_button.gml
Labels: device-gamepad 🎾

#785 Clamp raw gamepad axis value
  scripts/__input_class_gamepad/__input_class_gamepad.gml
Labels: device-gamepad 🎾
