Repository offalynne/Input, pull requests merged in 2023-10, with the labels that each got.

#789 Bump data
  datafiles/controllertypes.csv
  datafiles/sdl2.txt
  scripts/__input_gamepad_set_type/__input_gamepad_set_type.gml
Labels: feature :thought_balloon:, device-gamepad 🎾

#794 Address misconfigured touch source earlier, update error messages
  scripts/__input_finalize_default_profiles/__input_finalize_default_profiles.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
  scripts/input_profile_reset_bindings/input_profile_reset_bindings.gml
Labels: bug :sweat_smile:, feature :thought_balloon:, device-touch 🦔

#804 Update input_binding_set_safe.gml
  scripts/input_binding_set_safe/input_binding_set_safe.gml
Labels: bug :sweat_smile:

#803 Update license fetch
  LICENSE
  datafiles/input_license.txt
  refresh_datafiles.py
Labels: bug :sweat_smile:

#807 Update input_binding_swap.gml
  scripts/input_binding_swap/input_binding_swap.gml
Labels: bug :sweat_smile:, documentation ✏️

#806 Adds 'player using' aliases
  input.yyp
  scripts/input_player_using_gamepad/input_player_using_gamepad.gml
  scripts/input_player_using_gamepad/input_player_using_gamepad.yy
  scripts/input_player_using_keyboard/input_player_using_keyboard.gml
  scripts/input_player_using_keyboard/input_player_using_keyboard.yy
  scripts/input_player_using_mouse/input_player_using_mouse.gml
  scripts/input_player_using_mouse/input_player_using_mouse.yy
  scripts/input_player_using_touch/input_player_using_touch.gml
  scripts/input_player_using_touch/input_player_using_touch.yy
Labels: feature :thought_balloon:

#802 Simplify touch configuration
  scripts/__input_finalize_default_profiles/__input_finalize_default_profiles.gml
  scripts/__input_initialize/__input_initialize.gml
  scripts/__input_macros/__input_macros.gml
Labels: feature :thought_balloon:, platform-android 🤖, platform-ios 📱, platform-console 📦, device-mouse 🐈, device-touch 🦔, platform-desktop-native 🖥️

#817 Small correction in DPAD virtual button 4dir usability.
  docs/5.5/Functions-(Virtual-Buttons).md
  docs/5.6/Functions-(Virtual-Buttons).md
  docs/6.0/Functions-(Virtual-Button-Setup).md
  docs/6.1/Functions-(Virtual-Button-Setup).md
  docs/6.2/Functions-(Virtual-Button-Setup).md
Labels: bug :sweat_smile:, documentation ✏️

#815 Sustain hold across SystemGestureGate timeout on iOS
  scripts/__input_class_virtual/__input_class_virtual.gml
Labels: upstream bug 💧, platform-ios 📱, device-touch 🦔
