Repository offalynne/Input, pull requests merged in 2025-04, with the labels that each got.

#906 Bump data
  datafiles/gamecontrollerdb.txt
  refresh_data.py
  scripts/__InputCreateTypeLookup/__InputCreateTypeLookup.gml
Labels: device-gamepad 🎾

#902 Normalise magnitude per thresholds
  scripts/__InputClassPlayer/__InputClassPlayer.gml
Labels: bug :sweat_smile:, device-gamepad 🎾

#914 Swap ignore/allow structs for arrays in `InputDeviceSetRebinding()`
  scripts/InputDeviceSetRebinding/InputDeviceSetRebinding.gml
  scripts/__InputBindingScan/__InputBindingScan.gml
  scripts/__InputClassRebindingHandler/__InputClassRebindingHandler.gml
Labels: feature :thought_balloon:

#916 Add support for checking all verbs to `Input*Many()`
  input.yyp
  objects/objTest006_ManyCheckers/Draw_0.gml
  objects/objTest006_ManyCheckers/objTest006_ManyCheckers.yy
  scripts/InputCheckMany/InputCheckMany.gml
  scripts/InputDefineVerb/InputDefineVerb.gml
  scripts/InputPressedMany/InputPressedMany.gml
  scripts/InputReleasedMany/InputReleasedMany.gml
  scripts/__InputSystem/__InputSystem.gml
Labels: feature :thought_balloon:, request ❓

#915 Fix infinite loop in `InputCheckMany()`
  scripts/InputCheckMany/InputCheckMany.gml
Labels: bug :sweat_smile:

#917 `InputMostRecent()` and `InputLast()`
  input.yyp
  objects/objTest006_ManyCheckers/Draw_0.gml
  objects/objTest006_ManyCheckers/objTest006_ManyCheckers.yy
  scripts/InputCheckMany/InputCheckMany.gml
  scripts/InputDefineVerb/InputDefineVerb.gml
  scripts/InputLast/InputLast.gml
  scripts/InputLast/InputLast.yy
  scripts/InputMostRecent/InputMostRecent.gml
  scripts/InputMostRecent/InputMostRecent.yy
  scripts/InputPressedMany/InputPressedMany.gml
  scripts/InputReleasedMany/InputReleasedMany.gml
  scripts/__InputSystem/__InputSystem.gml
Labels: feature :thought_balloon:

#924 Support Array Copy on Write
  options/main/options_main.yy
  scripts/InputPlugInGamepadNullifyAllMappings/InputPlugInGamepadNullifyAllMappings.gml
  scripts/InputPlugInGamepadNullifyMapping/InputPlugInGamepadNullifyMapping.gml
  scripts/InputPlugInGamepadResetMapping/InputPlugInGamepadResetMapping.gml
  scripts/InputPlugInGamepadSetMapping/InputPlugInGamepadSetMapping.gml
  scripts/__InputBindingScan/__InputBindingScan.gml
  scripts/__InputClassPlayer/__InputClassPlayer.gml
  scripts/__InputClassVerbDefinition/__InputClassVerbDefinition.gml
  scripts/__InputClassVirtualButton/__InputClassVirtualButton.gml
  scripts/__InputRegisterGamepadConnected/__InputRegisterGamepadConnected.gml
  scripts/__InputRegisterGamepadDisconnected/__InputRegisterGamepadDisconnected.gml
Labels: bug :sweat_smile:

#927 Fixes crash on boot when verb indexes are discontinuous
  scripts/InputBindingsExport/InputBindingsExport.gml
  scripts/InputBindingsImport/InputBindingsImport.gml
  scripts/InputBindingsReset/InputBindingsReset.gml
  scripts/__InputClassPlayer/__InputClassPlayer.gml
Labels: bug :sweat_smile:
